# Convenience wrapper around CMake — not a replacement for it.
# Plain `make` lists the available targets.

.DEFAULT_GOAL := help
MAKEFLAGS += --no-print-directory

# Optional host-side overrides (PODMAN, BUILD_IMAGE, WIN_TYPE, ...)
-include local.properties

# Combined build image — one AlmaLinux 8 image for both Windows and Linux
# portable builds. See docker/ for the Dockerfile and deps.
# ---------------------------------------------------------------------------
PODMAN      ?= podman
BUILD_IMAGE ?= blitzview-build

# The build identity for the portable archive names. It is generated by
# cmake/GenerateBuildInfo.cmake on every build (git describe --tags --long
# --dirty) and written to
# <builddir>/generated/identity.txt — the same string the About dialog shows
# via BLITZVIEW_IDENTITY. Falls back to "Unknown" if it is not there yet.
identity = $(shell cat $(1)/generated/identity.txt 2>/dev/null || echo Unknown)

.PHONY: help build release clean \
        build-image build-image-force \
        windows windows-deploy windows-portable windows-clean \
        linux linux-deploy linux-portable linux-clean \
        dist-linux dist-windows

help: ## List available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "} {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

# Native host builds — all live under the single ./build directory, one
# subdirectory per build type.
BUILD_TYPE ?= Debug
DEV_DIR    := build/$(shell echo $(BUILD_TYPE) | tr A-Z a-z)

build: ## Configure ./build/$(TYPE) and compile BlitzView (TYPE=Debug default)
	cmake -B $(DEV_DIR) -DCMAKE_BUILD_TYPE=$(BUILD_TYPE)
	cmake --build $(DEV_DIR) --parallel

release: ## Same as 'make build' with TYPE=Release (asserts off, fast)
	@$(MAKE) build BUILD_TYPE=Release

clean: ## Remove the ./build directory
	rm -rf build

# ---------------------------------------------------------------------------
# Portable build image — one AlmaLinux 8 image for both Windows and Linux
# portable builds. See docker/ for the Dockerfile and deps.
# ---------------------------------------------------------------------------
build-image: ## Build the combined builder image if it doesn't exist yet (AlmaLinux 8, glibc 2.28)
	@$(PODMAN) image inspect $(BUILD_IMAGE) >/dev/null 2>&1 || $(MAKE) build-image-force

build-image-force: ## Rebuild the builder image unconditionally (after changing docker/)
	$(PODMAN) build -f docker/Dockerfile -t $(BUILD_IMAGE) .

# ---------------------------------------------------------------------------
# Windows build (cross-compile via MinGW, see winbuild/ and cmake/toolchain-mingw.cmake)
# ---------------------------------------------------------------------------
WIN_TYPE    ?= Release
WIN_DIR     := build/windows
WIN_DIST    := dist/windows

# BuildInfo.h is generated on the HOST, not inside the container: the builder
# image has no git, yet the About dialog must show the true host-side commit,
# dirty state and build time. cmake/GenerateBuildInfo.cmake is the single
# generation script for both platforms.

windows: build-image $(WIN_DIR)/icon.ico ## Cross-build blitzview.exe into ./build/windows
	@if [ -f $(WIN_DIR)/CMakeCache.txt ] && \
	    [ "$$(stat -c '%u' $(WIN_DIR)/CMakeCache.txt)" != "$$(id -u)" ]; then \
	    echo "$(WIN_DIR) owned by a different user, removing it ..."; \
	    rm -rf $(WIN_DIR); \
	fi
	@mkdir -p $(WIN_DIR)/generated
	@cmake -D "BV_SOURCE_DIR=$(CURDIR)" \
	    -D "BV_OUTPUT=$(CURDIR)/$(WIN_DIR)/generated/BuildInfo.h" \
	    -P cmake/GenerateBuildInfo.cmake
	$(PODMAN) run --rm \
	    -v "$$(pwd):/project:rw,z" \
	    -e PROJECT=/project \
	    -e BUILD_DIR=/project/$(WIN_DIR) \
	    -e BUILD_TYPE=$(WIN_TYPE) \
	    $(BUILD_IMAGE) sh /project/winbuild/build.sh

# The launcher's Explorer icon. Generated from the app icon rather than
# checked in, so the two cannot drift apart.
$(WIN_DIR)/icon.ico: res/BlitzViewIcon.png | $(WIN_DIR)
	@if command -v magick >/dev/null 2>&1; then \
	    magick $< -define icon:auto-resize=256,128,64,48,32,16 $@; \
	elif command -v convert >/dev/null 2>&1; then \
	    convert $< -define icon:auto-resize=256,128,64,48,32,16 $@; \
	else \
	    echo "ImageMagick not found - launcher will have no icon"; \
	fi

$(WIN_DIR):
	@mkdir -p $(WIN_DIR)

windows-deploy: windows ## Bundle Qt DLLs + plugins into build/windows/BlitzView
	$(PODMAN) run --rm \
	    -v "$$(pwd):/project:rw,z" \
	    -e PROJECT=/project \
	    -e BUILD_DIR=/project/$(WIN_DIR) \
	    $(BUILD_IMAGE) sh /project/winbuild/deploy.sh

windows-portable: windows-deploy ## Zip the portable package into dist/windows/
	@mkdir -p $(WIN_DIST)
	@rm -f $(WIN_DIST)/BlitzView-Windows-$(call identity,$(WIN_DIR)).zip
	@mv $(WIN_DIR)/BlitzView $(WIN_DIR)/BlitzView-$(call identity,$(WIN_DIR))
	cd $(WIN_DIR) && zip -q -r $(CURDIR)/$(WIN_DIST)/BlitzView-Windows-$(call identity,$(WIN_DIR)).zip BlitzView-$(call identity,$(WIN_DIR))
	@mv $(WIN_DIR)/BlitzView-$(call identity,$(WIN_DIR)) $(WIN_DIR)/BlitzView
	@ls -lh $(WIN_DIST)/BlitzView-Windows-$(call identity,$(WIN_DIR)).zip

windows-clean: ## Remove ./build/windows and ./dist/windows
	rm -rf $(WIN_DIR) $(WIN_DIST)

# ---------------------------------------------------------------------------
# Linux build (native container build, see linuxbuild/)
# ---------------------------------------------------------------------------
LINUX_TYPE  ?= Release
LINUX_DIR   := build/linux
LINUX_DIST  := dist/linux

linux: build-image ## Build blitzview into ./build/linux
	@if [ -f $(LINUX_DIR)/CMakeCache.txt ] && \
	    [ "$$(stat -c '%u' $(LINUX_DIR)/CMakeCache.txt)" != "$$(id -u)" ]; then \
	    echo "$(LINUX_DIR) owned by a different user, removing it ..."; \
	    rm -rf $(LINUX_DIR); \
	fi
	@mkdir -p $(LINUX_DIR)/generated
	@cmake -D "BV_SOURCE_DIR=$(CURDIR)" \
	    -D "BV_OUTPUT=$(CURDIR)/$(LINUX_DIR)/generated/BuildInfo.h" \
	    -P cmake/GenerateBuildInfo.cmake
	$(PODMAN) run --rm \
	    -v "$$(pwd):/project:rw,z" \
	    -e PROJECT=/project \
	    -e BUILD_DIR=/project/$(LINUX_DIR) \
	    -e BUILD_TYPE=$(LINUX_TYPE) \
	    $(BUILD_IMAGE) sh /project/linuxbuild/build.sh

linux-deploy: linux ## Bundle Qt + FFmpeg libs + plugins into build/linux/BlitzView
	$(PODMAN) run --rm \
	    -v "$$(pwd):/project:rw,z" \
	    -e PROJECT=/project \
	    -e BUILD_DIR=/project/$(LINUX_DIR) \
	    $(BUILD_IMAGE) sh /project/linuxbuild/deploy.sh

linux-portable: linux-deploy ## Tar.gz the portable package into dist/linux/
	@mkdir -p $(LINUX_DIST)
	@rm -f $(LINUX_DIST)/BlitzView-Linux-$(call identity,$(LINUX_DIR)).tar.gz
	cd $(LINUX_DIR) && tar czf $(CURDIR)/$(LINUX_DIST)/BlitzView-Linux-$(call identity,$(LINUX_DIR)).tar.gz \
	    --transform 's,^BlitzView,BlitzView-$(call identity,$(LINUX_DIR)),' BlitzView
	@ls -lh $(LINUX_DIST)/BlitzView-Linux-$(call identity,$(LINUX_DIR)).tar.gz

linux-clean: ## Remove ./build/linux and ./dist/linux
	rm -rf $(LINUX_DIR) $(LINUX_DIST)

dist-linux: linux-portable ## Alias for linux-portable
dist-windows: windows-portable ## Alias for windows-portable
