#!/bin/sh
# Downloads upstream FFmpeg headers (no library build) matching the version
# Qt bundles, into $1. The Linux/Windows portable builds get the same headers
# baked into the shared Docker image (see docker/deps.sh); this script does
# the equivalent for a native macOS runner, reusing the same pinned
# version/URL/hash from docker/deps.env so all three platforms track one
# FFmpeg release.
set -eu

DEST=${1:?"usage: fetch-ffmpeg-headers.sh <dest-include-dir>"}
PROJECT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

. "$PROJECT/docker/deps.env"

if [ -f "$DEST/libavcodec/avcodec.h" ]; then
    echo "FFmpeg headers already at $DEST"
    exit 0
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

curl -L -o "$TMP/ffmpeg-src.tar.xz" "$FFMPEG_SRC_URL"
echo "$FFMPEG_SRC_SHA256  $TMP/ffmpeg-src.tar.xz" | shasum -a 256 -c -
tar xJf "$TMP/ffmpeg-src.tar.xz" -C "$TMP"

mkdir -p "$DEST"
for lib in libavcodec libavformat libavutil libswscale libswresample; do
    mkdir -p "$DEST/$lib"
    cp "$TMP/ffmpeg-$FFMPEG_VERSION/$lib"/*.h "$DEST/$lib/"
done

# avconfig.h is generated by ./configure and absent from the source tarball,
# but public headers include it. Two defines, fixed for x86_64/arm64 (both
# little-endian with fast unaligned access) -- see docker/deps.sh, same file.
cat > "$DEST/libavutil/avconfig.h" <<'EOF'
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif
EOF

echo "FFmpeg headers at $DEST:"
ls "$DEST"
