#!/bin/sh
# Runs at IMAGE BUILD time. Installs:
#   - Qt 6.8.3 for BOTH platforms (Linux native + Windows cross-compile)
#   - AmanoTeam MinGW cross-compiler (GCC 16, Linux-hosted)
#   - FFmpeg 7.1.1 headers (matching Qt's bundled FFmpeg)
#
# This script runs once; the resulting image serves both build targets.
set -eux

. /usr/src/deps.env

QT_LINUX_PREFIX="/opt/qt/$QT_VERSION/gcc_64"
QT_WINDOWS_PREFIX="/opt/qt/$QT_VERSION/mingw_64"

# ---------------------------------------------------------------------------
# Qt 6.8.3 for Linux (native) — host tools for cross-compile + Linux build.
# ---------------------------------------------------------------------------
mkdir -p /opt/qt
# shellcheck disable=SC2086  # QT_MODULES_LINUX is a deliberate word list
aqt install-qt linux desktop "$QT_VERSION" "$QT_ARCH_LINUX" \
    -m $QT_MODULES_LINUX -O /opt/qt

echo "--- Linux Qt installed at: $QT_LINUX_PREFIX"
ls "$QT_LINUX_PREFIX/lib/cmake/" | grep -E '^Qt6[A-Z]' | head -20

# ---------------------------------------------------------------------------
# Qt 6.8.3 for Windows (cross-compile target) — headers, libs, cmake files.
# ---------------------------------------------------------------------------
# shellcheck disable=SC2086  # QT_MODULES_WINDOWS is a deliberate word list
aqt install-qt windows desktop "$QT_VERSION" "$QT_ARCH_WINDOWS" \
    -m $QT_MODULES_WINDOWS -O /opt/qt

echo "--- Windows Qt installed at: $QT_WINDOWS_PREFIX"

# ---------------------------------------------------------------------------
# MinGW cross-compiler — Linux-hosted ELF binaries from AmanoTeam.
# GCC 16.2.1 targeting Win64. ABI-compatible with Qt 6.8.3's GCC 13.1.
# ---------------------------------------------------------------------------
echo "--- Downloading MinGW cross-compiler ($MINGW_CROSS_VERSION) ---"
curl -L -o /tmp/mingw.tar.xz "$MINGW_CROSS_URL"
mkdir -p /opt/mingw
tar xf /tmp/mingw.tar.xz -C /opt/mingw --strip-components=1
rm /tmp/mingw.tar.xz

echo "--- Cross-compiler:"
/opt/mingw/bin/x86_64-w64-mingw32-gcc --version | head -1
echo "--- CRT libs:"
ls /opt/mingw/x86_64-w64-mingw32/lib/ | head -10

# ---------------------------------------------------------------------------
# FFmpeg HEADERS ONLY — same version as Qt's bundled FFmpeg 7.x.
#
# On Linux, Qt bundles libavcodec.so.61 / libavformat.so.61 etc. but provides
# no headers. We download matching upstream headers so BlitzView can compile
# against them. The actual .so files come from the Qt prefix at deploy time.
#
# On Windows this is the same situation: Qt ships the DLLs but no headers.
# ---------------------------------------------------------------------------
cd /tmp
curl -L -o ffmpeg-src.tar.xz "$FFMPEG_SRC_URL"
echo "$FFMPEG_SRC_SHA256  ffmpeg-src.tar.xz" | sha256sum -c -
tar xJf ffmpeg-src.tar.xz
mkdir -p /opt/ffmpeg/include
for lib in libavcodec libavformat libavutil libswscale libswresample; do
    mkdir -p "/opt/ffmpeg/include/$lib"
    cp "ffmpeg-$FFMPEG_VERSION/$lib"/*.h "/opt/ffmpeg/include/$lib/"
done

# avconfig.h is generated by ./configure and absent from the source tarball,
# but public headers include it. Two defines, fixed for x86_64.
cat > /opt/ffmpeg/include/libavutil/avconfig.h <<'EOF'
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif
EOF

rm -rf /tmp/ffmpeg-src.tar.xz "/tmp/ffmpeg-$FFMPEG_VERSION"

echo "--- FFmpeg headers at /opt/ffmpeg/include:"
ls /opt/ffmpeg/include/

# ---------------------------------------------------------------------------
# Report: Qt's bundled FFmpeg .so files (what we link against).
# ---------------------------------------------------------------------------
echo "--- Linux Qt bundled FFmpeg libraries:"
ls "$QT_LINUX_PREFIX/lib/"lib{avcodec,avformat,avutil,swscale,swresample}.so* 2>/dev/null || true

echo "--- Windows Qt bundled FFmpeg DLLs:"
ls "$QT_WINDOWS_PREFIX/bin/" | grep -E '^(av|sw)[a-z]+-[0-9]+\.dll$'

echo "DEPS OK: Qt $QT_VERSION + MinGW $MINGW_CROSS_VERSION installed"
